# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20171110_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='static/img/blog_img/'),
        ),
    ]
