# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20171112_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=None, upload_to='Post/blog_img/'),
        ),
    ]
